### ISSUE TITLE
Feature Request: Add pre-commit hook

### ISSUE THREAD

**Issue by aairey** [liamg/tfsec#105]
Hi, 

Could you add a pre-commit hook config file to this repo, similar to [checkov's file](https://github.com/bridgecrewio/checkov/blob/master/.pre-commit-hooks.yaml)?

This way we can use it in our pre-commit hooks.
See https://pre-commit.com/#new-hooks for more information.

**Comment by WassimKallel** [comment]
Hi, It is cool if there's an official support for pre-commit hooks from the tfsec team,  but there's this repo [https://github.com/antonbabenko/pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform) which combines more validation options.

I've been using it and it works great.

**Comment by aairey** [comment]
I was already using this repo and didn't realise ... thanks!
