### ISSUE TITLE
 undefined: strings.ReplaceAll

### ISSUE THREAD

**Issue by obiany** [liamg/tfsec#108]
I'm getting this error on installation

$ env GO111MODULE=on go get -u github.com/liamg/tfsec/cmd/tfsec

github.com/liamg/tfsec/internal/app/tfsec/scanner
go/src/github.com/liamg/tfsec/internal/app/tfsec/scanner/scanner.go:58:28: undefined: strings.ReplaceAll

**Comment by liamg** [comment]
Hi @obiany - you will need Go 1.12+ to build tfsec (this is when `strings.ReplaceAll` was added). I recommend using the latest version.
