### ISSUE TITLE
Publish image in Docker Hub

### ISSUE THREAD

**Issue by Maks3w** [liamg/tfsec#111]
I suggest automatic deployment of the Dockerfile in Docker Hub.

This is a more easier way of start to use the tool without to clone the repo and perform manual steps.

Integration in Docker Hub is as faster as link both repos so Docker Hub starts to build new images as branch pushes occurs

https://docs.docker.com/docker-hub/builds/

**Comment by iilei** [comment]
Also, I would love to see git tags aligned with version as seen in `version/version.go`

**Comment by liamg** [comment]
@Maks3w Thanks, have been meaning to do this for a while. Tags will reflect the binary version as requested by @iilei :+1:
