### ISSUE TITLE
"Check skipped due to errors" not output to stderr

### ISSUE THREAD

**Issue by clar-cmp** [liamg/tfsec#119]
And as a result, junit-format output is no longer valid, because it contains these strings.

Example output:

```
WARNING: skipped AWS006 check due to error(s): value is null
<?xml version="1.0" encoding="UTF-8"?>

<testsuite name="tfsec"></testsuite>
```

**Comment by clar-cmp** [comment]
Apparently the offending line is here: https://github.com/liamg/tfsec/blob/a450c423747c1ec2ef3cb52c1a270b05f2f5a62f/internal/app/tfsec/scanner/check.go#L28

**Comment by thiagoalmeidasa** [comment]
It still happens on version `liamg/tfsec:v0.36.6`

example cli:
```
docker run --rm -it -v "$(pwd):/src" liamg/tfsec:v0.36.6 /src --exclude MY_RULE --format junit > out.xml
```

`out.xml` content:
```
WARNING: skipped MY_RULE check due to error(s): value is null
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tfsec" failures="0" tests="0"></testsuite>
```
