### ISSUE TITLE
Docker: open /proc/tty/driver: permission denied when run as unprivileged user

### ISSUE THREAD

**Issue by abohne** [liamg/tfsec#140]
I'm attempting to run the docker image as an unprivileged user on Amazon Linux 2.

I'm attempting to execute the following command:
```docker run --rm -t -v $(pwd):/workdir liamg/tfsec:latest .```

I receive the following error:
```open /proc/tty/driver: permission denied when run as unprivileged user```

I can confirm that this directory is only accessible by root.
```[root@ip-xxx-xxx-xxx-xxx ~]# ls -la /proc/tty/driver
total 0
dr-x------ 2 root root 0 Jul 24 17:57 .
dr-xr-xr-x 4 root root 0 Jul 24 17:57 ..
-r--r--r-- 1 root root 0 Jul 24 17:57 serial
```

I get the same results if I remove the `-t`.

Any ideas what's causing this?

**Comment by liamg** [comment]
I think it's because you're mounting your code to scan at `/workdir` but then initiating the scan at `.` which will be `/`.

Try doing `docker run --rm -it -v "$(pwd):/src" liamg/tfsec:latest /src`

**Comment by abohne** [comment]
@liamg Your solution worked.

Thanks for the quick response!
