### ISSUE TITLE
Add Support for TLSv1.2_2019

### ISSUE THREAD

**Issue by mhester-nutrien** [liamg/tfsec#152]
![Screen Shot 2020-08-13 at 11 18 39 AM](https://user-images.githubusercontent.com/62255897/90166394-68e5b800-dd57-11ea-9a87-0f564e2872cc.jpg)

AWS now has "TLSv1.2_2019" available and uses it as the default. I am receiving the attached Problem notice from tfsec when using the 2019 version instead of 2018.

I think it is safe to say that use of the 2019 version should not be considered "outdated"

**Comment by bulebuk** [comment]
The Cloudfront console now shows TLSv1.2_2019 as 'recommended'.
