### ISSUE TITLE
Ensure CloudFront distribution SSL protocol is not outdated

### ISSUE THREAD

**Issue by reedloden** [liamg/tfsec#44]
`aws_cloudfront_distribution` supports `minimum_protocol_version`. Should ensure that TLSv1.2 is used (`TLSv1.2_2018`), or more specifically, that insecure/outdated protocols are not used.

https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#viewer-certificate-arguments

**Comment by 0xalexdelgado** [comment]
@liamg can I take this?

**Comment by liamg** [comment]
@0xalexdelgado Go for it! :rocket:

**Comment by 0xalexdelgado** [comment]
I forgot to close this in PR #80  again :( can you close it whenever you get a chance @liamg
