### ISSUE TITLE
Ensure CloudFront distribution only responds to HTTPS

### ISSUE THREAD

**Issue by reedloden** [liamg/tfsec#45]
`aws_cloudfront_distribution` supports `viewer_protocol_policy`. Should ensure that only HTTPS is supported.

https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#viewer_protocol_policy

**Comment by 0xalexdelgado** [comment]
@liamg can I take this?

**Comment by liamg** [comment]
@0xalexdelgado Go for it! Thank you :+1:

**Comment by 0xalexdelgado** [comment]
When you get a chance can you close this @liamg? I forgot to mark my PR with `resolves..`

Thank you!
