### ISSUE TITLE
No color output mode

### ISSUE THREAD

**Issue by glindstedt** [liamg/tfsec#50]
I'd like to be able to get the output without any syntax highlighting. This is useful for simple copy-pasting by piping to something like `pbcopy`/`xsel`/`xclip`, but may also be better for certain CI systems that don't handle escape sequences well.

The `terraform plan` command has a `-no-color` argument, I would suggest to mirror that.

**Comment by liamg** [comment]
Thanks @glindstedt!

I've added a `--no-color` flag (and an aliased `--no-colour` flag too so I don't freak out.)

**Comment by glindstedt** [comment]
Awesome, thanks @liamg!

**Comment by aldwyn** [comment]
Hi @liamg, `--no-color` still gives off ANSI escape codes when being shown in Azure Repo preformatted-text outputs.

![image](https://user-images.githubusercontent.com/7032430/132935491-209f8da4-14ec-4995-9fbd-b22436f8935d.png)
