### ISSUE TITLE
Not returning detail from multiple diagnostics

### ISSUE THREAD

**Issue by RangerDan** [liamg/tfsec#53]
When running the scan against a single or multiple repositories, the result is not formatted like the example, and it only displays one result.

```
PS C:\Users\Me\Projects\TF> tfsec .\tf-use-svc\
C:\Users\Me\Projects\TF\tf-use-svc\main.tf:30,3-12: Attribute redefined; The argument "statement" was already set at C:\Users\Me\Projects\TF\tf-use-svc\main.tf:19,3-12. Each argument may be set only once., and 3 other diagnostic(s)
```

Tested with v0.1.0 on both WSL and Powershell, Windows 10

**Comment by RangerDan** [comment]
(new to TF, not my codebase)

Is this a problem in my TF for a problem in the scanner?  How would I tell?

**Comment by reedloden** [comment]
That's an issue in your own Terraform code. Looks like you're reusing `statement` twice within the same block.

**Comment by liamg** [comment]
It may also be Terraform version 0.11 code - at the moment tfsec only supports 0.12+ (HCL v2)
