### ISSUE TITLE
Add Homebrew / Linuxbrew formula

### ISSUE THREAD

**Issue by reedloden** [liamg/tfsec#54]
To make this easier to use, would be great to have a Homebrew / Linuxbrew formula added.

End goal would the ability to do:
```shell
$ brew tap liamg/tfsec
$ brew install tfsec
```

References:
* https://gist.github.com/mickep76/ca29cca70f0b458aee4d
* https://jkawamoto.github.io/fgo/

**Comment by liamg** [comment]
Thanks @reedloden!

You can now: `brew tap liamg/tfsec && brew install liamg/tfsec/tfsec`
