### ISSUE TITLE
Add Dockerfile so that tfsec may run in a container

### ISSUE THREAD

**Issue by wesley-dean-flexion** [liamg/tfsec#56]
First, thank you very much for putting tfsec together!  I was very pleased to have stumbled across it the other day.

In general, I try to run most tools inside of Docker containers, both from my IDE and from my CI/CD tools.  It would be pretty nifty if tfsec could run inside of a container; it would be similarly nifty if one drafted a Dockerfile to make that happen.

To that end, I put together a quick Dockerfile and included it in a PR: #55

**Comment by wesley-dean-flexion** [comment]
Also, if it's cool with you, I would like to push the resulting image on to hub.docker.com so that folks -- myself included -- can pull the image and run it rather than have to (re-)build it unnecessarily.  I'll happily update the documentation to show this workflow, too.

**Comment by liamg** [comment]
Added in #55
