### ISSUE TITLE
AWS005: clarrification / documentation

### ISSUE THREAD

**Issue by vkruoso** [liamg/tfsec#71]
Hi! Rule AWS005 seems strange for me. One of the reasons to have a LB is to expose application without exposing the actual instances. If the application is internet facing, them the LB needs to be exposed. Is there any documents on AWS on what is the best practice?

Also, not only for this rule, but for all of them, it would be great if we can have more information within the rule itself so it is easier to understand why the rule triggered (maybe display a URL to the docs in the actual error like eslint).

**Comment by vkruoso** [comment]
Found this: https://www.cloudconformity.com/knowledge-base/aws/ELB/internet-facing-load-balancers.html

**Comment by liamg** [comment]
This is there primarily for awareness of public exposure rather than highlighting a definite issue. It's definitely a good idea to add a bit more information to each rule. I'll try and get to this soon.

**Comment by liamg** [comment]
The AWS005 rule now has a link to the wiki which includes the link you gave above - thank you!
