### ISSUE TITLE
Feature request: Exclude rules via CLI arguments

### ISSUE THREAD

**Issue by kmcquade** [liamg/tfsec#78]
Hi, great project. I'd like to make a request. Right now, to exclude rules, you have to modify the code to "a comment containing `tfsec:ignore:<RULE>` to the offending line in your templates", per the README. It would be very useful if we could do this via CLI args as well, for assessment purposes.

**Comment by destornillador** [comment]
I agree with @kmcquade . It would be also helpful if we can explicitly exclude rules from a tfsec file (let's say `.tfsec`). 

In my use case, I have 50+ Terraform modules re-using one CI Pipeline code. I have some modules that need to have a fully open ingress rule and others don't. So, excluding this rule only in some Terraform Modules using a `.tfsec` in their repository, would be the best option.

Thank you

**Comment by edersonbrilhante** [comment]
Also could be added the option to ignore some files or folders.

**Comment by richard-senior** [comment]
Yes please... we need to be able to exclude specific rules by argument when using the [python pre-commit framework](https://pre-commit.com/).
Something like :
 - id: terraform_tflint
    args: ['args=--AWS004']

etc.

**Comment by owenrumney** [comment]
@liamg  - this looks like it was resolved with 

Exclude Checks - https://github.com/liamg/tfsec/pull/98
and 
Exclude Directories - https://github.com/liamg/tfsec/pull/129

**Comment by liamg** [comment]
@owenrumney Yep, looks to be resolved there - thanks :+1:
