### ISSUE TITLE
check skipped due to errors

### ISSUE THREAD

**Issue by bootswithdefer** [liamg/tfsec#83]
This resource causes the error `WARNING: skipped AWS006 check due to error(s): value is null` because the cidr_blocks is not a list of strings.  In this example the cidr_blocks is a list of strings returned from a module.

```
resource "aws_security_group_rule" "github" {
  description = "HTTPS (GitHub)"
  type        = "ingress"
  from_port   = 443
  to_port     = 443
  protocol    = "tcp"
  cidr_blocks = module.ips.github

  security_group_id = aws_security_group.sg.id
}
```

**Comment by mpiala** [comment]
Receiving same error when using concat in cidr_blocks:

```
WARNING: skipped AWS008 check due to error(s): value is null
WARNING: skipped AWS009 check due to error(s): value is null

No problems detected!

0 potential problems detected:
```

It's enough when there is only one `cidr_blocks = concat(x)` in whole aws_security_group. Example where failing:
```
resource "aws_security_group" "sg_dmz" {
  name        = "name"
  description = "g_dmz_desc"
  vpc_id      = "asdf"

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = concat(var.cidr_2, var.cidr_1)
    description = "Allowed HTTPS Traffic from internet"
  }

egress {
    from_port   = 25
    to_port     = 25
    protocol    = "tcp"
    cidr_blocks = concat(var.cidr_2, var.cidr_1)
    description = "Email sending to SMTP service"
  }
}

variable "cidr_1" {
  default = ["0.0.0.0/0"]
}
variable "cidr_2" {
  default = ["1.1.1.1/32"]
}
```

**Comment by liamg** [comment]
@mpiala Unfortunately the use of the Terraform functions e.g. `concat` isn't possible until this issue is resolved: https://github.com/hashicorp/terraform/issues/22341 - otherwise pulling in the terraform package through `go mod` fails :'(

Hoping to resolve this issue soon...

**Comment by liamg** [comment]
Scratch that, fixed it :D
