### ISSUE TITLE
Junit or simular output for Jenkins

### ISSUE THREAD

**Issue by jverhoeks** [liamg/tfsec#85]
Have the errors in junit format makes it easy to integrate in the jenkins or other ci/cd pipelines

**Comment by samm-git** [comment]
+1, also will help for the circleci test results

**Comment by MorganGeek** [comment]
+1 as well. I'm using checkov and tfsec for my terraform and terragrunt pipelines :-) , checkov provides an option for getting outputs in junit format, it would be awesome to have the same with tfsec !

**Comment by samm-git** [comment]
Ok, it seems to be trivial change, will try to do next days

**Comment by samm-git** [comment]
Done, feel free to test my PR. So far tested with CircleCI only, both enterprise and saas.

**Comment by MorganGeek** [comment]
Thank you @samm-git  :) 🤟

**Comment by wheelq** [comment]
> +1 as well. I'm using checkov and tfsec for my terraform and terragrunt pipelines :-) , checkov provides an option for getting outputs in junit format, it would be awesome to have the same with tfsec !

Are you using tfsec and checkov simultaneously?

**Comment by MorganGeek** [comment]
> > +1 as well. I'm using checkov and tfsec for my terraform and terragrunt pipelines :-) , checkov provides an option for getting outputs in junit format, it would be awesome to have the same with tfsec !
> 
> Are you using tfsec and checkov simultaneously?

Yes :-)
