### ISSUE TITLE
Incorrect "Attribute redefined" error for aws_ami and aws_vpc

### ISSUE THREAD

**Issue by chadmyers** [liamg/tfsec#86]
Error:

```
(mypath)\_0_data.tf:41,3-9: Attribute redefined; The argument "filter" was already set at (mypath)\_0_data.tf:36,3-9. Each argument may be set only once.
```

Code in question:

```
data "aws_ami" "ubuntu" {
  most_recent = true

  filter = {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}
```

Relevant documentation section:
https://www.terraform.io/docs/providers/aws/d/ami.html

According to the docs, specifying more than filter segment is valid and supported and anyhow it works in practice.

I checked and I don't think there any other way to specify multiple filters for an AMI search in Terraform so I'm not sure how to fix this problem such that tfsec won't throw an error.

**Comment by chadmyers** [comment]
It is also complaining about this section:

```
data "aws_vpc" "my_vpc" {
  filter = {
    name   = "tag:Name"
    values = ["myvpc01"]
  }

  filter = {
    name   = "state"
    values = ["available"]
  }
}
```

Relevant documentation:
https://www.terraform.io/docs/providers/aws/d/vpc.html

Supports one or more filter blocks

**Comment by liamg** [comment]
Hi @chadmyers - I think you shouldn't be using those `=`, as that will assign an attribute rather than declare a block. So your first example should be:
```
data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}
```

**Comment by chadmyers** [comment]
@liamg Ah yes, dangit, that was it!  Thank you and sorry to have wasted your time!  Hopefully this will at least serve as a warning in case anyone else hits the same thing.

**Comment by liamg** [comment]
@chadmyers No problem, glad I could help!
